# Change these first
owner: evva-sfw # Your GitHub organization or username, where this repository lives
repo: xsm-status # The name of this repository

sites:
  - name: XMS Service
    url: https://mss.akx.cloud/health
  - name: XMS Broker
    check: "tcp-ping"
    url: mqtt.akx.cloud
    port: 443

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.akx.cloud
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/evva-sfw/upptime.js.org/master/static/img/icon.svg
  name: XMS Status
  introTitle: "**XMS** uptime monitor and status page."
  introMessage: This is a status and uptime page based on real-time monitoring data.
  navbar:
    - title: Status
      href: /
    - title: XMS
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
